title: SUPA WASD
author: odjacobs
email: 98474660+odjacobs@users.noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  We only discuss WASD and WASD related topics here. Perhaps the occasional ASDF

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  odjacobs # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima